using System.Globalization;
using System.Text;

namespace GameData.IDA.Codegen;

/// <summary>Writes the generated binding files.</summary>
/// <remarks>
/// The output is split along the seam that lets one assembly serve several SDK versions: the
/// <em>surface</em> — one field and one forwarder per symbol — is emitted once from the merged
/// declarations, while the <em>binder</em> — the <c>GetExport</c> calls that fill those fields — is
/// emitted once per vendored version into its own subdirectory. Selecting a version at load time is
/// then a matter of calling the right <c>BindAll_&lt;V&gt;</c>.
/// </remarks>
internal sealed class Emitter(string outputDir)
{
    private const string Namespace = "GameData.IDA.Core.Native";
    private const string Header = "// <auto-generated>\n" +
                                  "//     Generated by GameData.IDA.Codegen from the vendored IDA SDK headers.\n" +
                                  "//     Do not edit; re-run the generator instead.\n" +
                                  "// </auto-generated>";

    private readonly Dictionary<string, int> _boundPerVersion = new(StringComparer.Ordinal);
    private int _emitted;
    private int _dataEmitted;
    private int _guarded;

    /// <summary>Functions on the merged surface.</summary>
    internal int EmittedCount => _emitted;

    /// <summary>Data exports on the merged surface.</summary>
    internal int EmittedDataCount => _dataEmitted;

    /// <summary>Surface symbols that are not exported by every vendored version.</summary>
    internal int GuardedCount => _guarded;

    /// <summary>How many symbols each version's binder resolves, keyed by version.</summary>
    internal IReadOnlyDictionary<string, int> BoundPerVersion => _boundPerVersion;

    internal void Emit(
        MergedSurface surface,
        IReadOnlyList<SdkVersion> versions,
        IReadOnlyDictionary<string, IReadOnlyList<RenderedDecl>> perVersion,
        IReadOnlyCollection<string> opaqueTypes)
    {
        Directory.CreateDirectory(outputDir);

        foreach (string stale in Directory.EnumerateFiles(outputDir, "*.g.cs", SearchOption.AllDirectories))
        {
            File.Delete(stale);
        }

        var byName = surface.Entries.ToDictionary(e => e.Decl.Name, StringComparer.Ordinal);

        var groups = surface.Entries
            .GroupBy(e => e.Decl.Header)
            .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase)
            .ToList();

        foreach (var group in groups)
        {
            EmitSurfaceHeader(group.Key, [.. group], versions.Count);
        }

        foreach (var version in versions)
        {
            EmitBinder(version, groups, byName, perVersion[version.Key]);
        }

        EmitOpaque(opaqueTypes);
        EmitSdk(versions);
        PruneEmptyDirectories();
    }

    /// <summary>Writes one surface file: the fields and forwarders for one SDK header.</summary>
    private void EmitSurfaceHeader(string headerFile, IReadOnlyList<SurfaceEntry> entries, int versionCount)
    {
        string group = GroupName(headerFile);
        var body = new StringBuilder();

        foreach (var entry in entries)
        {
            RenderSurface(entry, versionCount, body);
        }

        var file = new StringBuilder();
        file.Append(Header).Append('\n');
        file.Append("// Source header: ").Append(headerFile).Append('\n');
        file.Append("\nnamespace ").Append(Namespace).Append(";\n\n");
        file.Append("public static unsafe partial class Ida\n{\n");
        file.Append(body);
        file.Append("}\n");

        File.WriteAllText(Path.Combine(outputDir, $"Ida.{group}.g.cs"), file.ToString());
    }

    private void RenderSurface(SurfaceEntry entry, int versionCount, StringBuilder body)
    {
        var decl = entry.Decl;
        bool universal = entry.IsUniversal(versionCount);

        if (decl.IsData)
        {
            body.Append("\n    /// <summary>").Append(Doc(decl)).Append("</summary>\n");
            AppendAvailability(entry, universal, body);
            body.Append("    public static ").Append(decl.FieldType).Append(' ').Append(decl.Method).Append(";\n");
            _dataEmitted++;

            if (!universal)
            {
                _guarded++;
            }

            return;
        }

        string parameters = string.Join(", ", decl.Parameters.Select(p => $"{p.Type} {p.Name}"));
        string arguments = string.Join(", ", decl.Parameters.Select(p => p.Name));

        body.Append("\n    private static ").Append(decl.FieldType).Append(' ').Append(decl.Field).Append(";\n\n");
        body.Append("    /// <summary>").Append(Doc(decl)).Append("</summary>\n");
        AppendAvailability(entry, universal, body);

        foreach (var parameter in decl.Parameters.Where(p => p.DefaultValue != null))
        {
            body.Append("    /// <param name=\"").Append(parameter.Name)
                .Append("\">Defaulted to <c>").Append(Escape(parameter.DefaultValue!)).Append("</c> in the header.</param>\n");
        }

        body.Append("    public static ").Append(decl.ReturnType).Append(' ').Append(decl.Method)
            .Append('(').Append(parameters).Append(')');

        if (universal)
        {
            body.Append(" => ").Append(decl.Field).Append('(').Append(arguments).Append(");\n");
        }
        else
        {
            // The field stays null on a version that does not export this symbol, so the guard is
            // what turns "wrong SDK for this call" into a named exception instead of a null jump.
            body.Append("\n    {\n        if (").Append(decl.Field).Append(" == null)\n        {\n")
                .Append("            throw NotBound(\"").Append(decl.Name).Append("\");\n        }\n\n")
                .Append("        ").Append(decl.ReturnType == "void" ? string.Empty : "return ")
                .Append(decl.Field).Append('(').Append(arguments).Append(");\n    }\n");

            _guarded++;
        }

        _emitted++;
    }

    /// <summary>Documents which SDK versions carry a symbol, for the ones that are not in all of them.</summary>
    private static void AppendAvailability(SurfaceEntry entry, bool universal, StringBuilder body)
    {
        if (universal)
        {
            return;
        }

        body.Append("    /// <remarks>Available in IDA ")
            .Append(string.Join(", ", entry.Versions.Select(v => v.Key)))
            .Append(" only.</remarks>\n");
    }

    /// <summary>Writes one version's binder: the <c>GetExport</c> calls that fill the surface fields.</summary>
    private void EmitBinder(
        SdkVersion version,
        IReadOnlyList<IGrouping<string, SurfaceEntry>> groups,
        IReadOnlyDictionary<string, SurfaceEntry> byName,
        IReadOnlyList<RenderedDecl> declarations)
    {
        string directory = Path.Combine(outputDir, version.Identifier);
        Directory.CreateDirectory(directory);

        // What this version actually exports, by symbol. Anything the merge dropped as a conflict
        // is absent from `byName` and so is bound by no version at all.
        var exported = declarations
            .Where(d => byName.ContainsKey(d.Name))
            .ToDictionary(d => d.Name, StringComparer.Ordinal);

        var emittedGroups = new List<string>();
        int bound = 0;

        foreach (var group in groups)
        {
            var binds = new StringBuilder();
            int count = 0;

            foreach (var entry in group)
            {
                if (!exported.TryGetValue(entry.Decl.Name, out var decl))
                {
                    continue;
                }

                string target = entry.Decl.IsData ? entry.Decl.Method : entry.Decl.Field;

                binds.Append("        ").Append(target).Append(" = (").Append(entry.Decl.FieldType)
                     .Append(")NativeLibrary.GetExport(").Append(decl.Handle)
                     .Append(", \"").Append(decl.Name).Append("\");\n");

                count++;
            }

            if (count == 0)
            {
                continue;
            }

            string name = GroupName(group.Key);
            emittedGroups.Add(name);
            bound += count;

            var file = new StringBuilder();
            file.Append(Header).Append('\n');
            file.Append("// Source header: ").Append(group.Key).Append('\n');
            file.Append("// SDK version: ").Append(version.Label).Append('\n');
            file.Append("\nusing System.Runtime.InteropServices;\n\n");
            file.Append("namespace ").Append(Namespace).Append(";\n\n");
            file.Append("public static unsafe partial class Ida\n{\n");
            file.Append("    private static void Bind_").Append(name).Append('_').Append(version.Identifier)
                .Append("(nint ida, nint idalib)\n    {\n");
            file.Append(binds);
            file.Append("    }\n}\n");

            File.WriteAllText(Path.Combine(directory, $"Ida.{name}.Bind.g.cs"), file.ToString());
        }

        _boundPerVersion[version.Key] = bound;

        var root = new StringBuilder();
        root.Append(Header).Append('\n');
        root.Append("// SDK version: ").Append(version.Label).Append('\n');
        root.Append("\nnamespace ").Append(Namespace).Append(";\n\n");
        root.Append("public static unsafe partial class Ida\n{\n");
        root.Append("    /// <summary>Number of native entry points the IDA ").Append(version.Key)
            .Append(" bindings resolve.</summary>\n");
        root.Append("    public const int ExportCount_").Append(version.Identifier).Append(" = ").Append(bound).Append(";\n\n");
        root.Append("    /// <summary>Resolves every IDA ").Append(version.Key)
            .Append(" entry point against the two loaded libraries.</summary>\n");
        root.Append("""
                /// <remarks>
                /// Binding is eager and unguarded on purpose. The generator only emits symbols it observed
                /// in this version's export table, so a <see cref="System.EntryPointNotFoundException"/>
                /// here names the exact symbol that proves the loaded libraries are not the build they
                /// report themselves to be — which is far more useful than a null call site later on.
                /// </remarks>

            """);
        root.Append("    private static void BindAll_").Append(version.Identifier).Append("(nint ida, nint idalib)\n    {\n");

        foreach (string name in emittedGroups)
        {
            root.Append("        Bind_").Append(name).Append('_').Append(version.Identifier).Append("(ida, idalib);\n");
        }

        root.Append("    }\n}\n");

        File.WriteAllText(Path.Combine(directory, "Ida.Bind.g.cs"), root.ToString());
    }

    private void EmitOpaque(IReadOnlyCollection<string> opaqueTypes)
    {
        var file = new StringBuilder();
        file.Append(Header).Append('\n');
        file.Append("\nnamespace ").Append(Namespace).Append(";\n\n");
        file.Append("""
            // Types the SDK only ever hands out behind a pointer. Each gets its own empty struct so a
            // `func_t*` cannot be passed where a `segment_t*` is expected. They are never dereferenced
            // and never instantiated; their layout is deliberately unknown to managed code.

            """);

        foreach (string name in opaqueTypes)
        {
            file.Append("/// <summary>Opaque IDA type <c>").Append(Escape(name)).Append("</c>.</summary>\n");
            file.Append("public readonly struct ").Append(name).Append(";\n\n");
        }

        File.WriteAllText(Path.Combine(outputDir, "Ida.Opaque.g.cs"), file.ToString());
    }

    /// <summary>Writes the version dispatch: which binder runs, and what this build was generated from.</summary>
    private void EmitSdk(IReadOnlyList<SdkVersion> versions)
    {
        var file = new StringBuilder();
        file.Append(Header).Append('\n');
        file.Append("\nusing GameData.IDA.Shared.Ida;\n\n");
        file.Append("namespace ").Append(Namespace).Append(";\n\n");
        file.Append("public static unsafe partial class Ida\n{\n");

        file.Append("    /// <summary>Number of native entry points the merged binding surface declares.</summary>\n");
        file.Append("    public const int SurfaceCount = ").Append(_emitted + _dataEmitted).Append(";\n\n");

        file.Append("    /// <summary>The SDK versions this build has binders for, oldest first.</summary>\n");
        file.Append("    public static readonly IdaSdkVersion[] GeneratedVersions =\n        [")
            .Append(string.Join(", ", versions.Select(v => "IdaSdkVersion." + v.Identifier)))
            .Append("];\n\n");

        file.Append("""
                /// <summary>The version whose binder last ran, or <c>Auto</c> before any has.</summary>
                public static IdaSdkVersion BoundVersion { get; private set; }

                /// <summary>Resolves every entry point one SDK version exports against the loaded libraries.</summary>
                /// <exception cref="NotSupportedException">No binder was generated for that version.</exception>
                internal static void BindAll(nint ida, nint idalib, IdaSdkVersion version)
                {
                    switch (version)
                    {

            """);

        foreach (var version in versions)
        {
            file.Append("            case IdaSdkVersion.").Append(version.Identifier)
                .Append(":\n                BindAll_").Append(version.Identifier).Append("(ida, idalib);\n")
                .Append("                break;\n\n");
        }

        file.Append("""
                        default:
                            throw new NotSupportedException(
                                $"This build has no IDA bindings for {version}.");
                    }

                    BoundVersion = version;
                }

            """);

        if (_guarded > 0)
        {
            file.Append("""
                    /// <summary>
                    /// Thrown by a forwarder whose symbol the bound SDK version does not export.
                    /// </summary>
                    private static Exception NotBound(string symbol)
                        => new EntryPointNotFoundException(
                            $"'{symbol}' is not exported by IDA {BoundVersion}.");

                """);
        }

        file.Append("}\n");

        File.WriteAllText(Path.Combine(outputDir, "Ida.Sdk.g.cs"), file.ToString());
    }

    /// <summary>Removes version directories left behind by a version that is no longer vendored.</summary>
    private void PruneEmptyDirectories()
    {
        foreach (string directory in Directory.EnumerateDirectories(outputDir))
        {
            if (!Directory.EnumerateFileSystemEntries(directory).Any())
            {
                Directory.Delete(directory);
            }
        }
    }

    private static string Doc(RenderedDecl decl)
        => $"{decl.Module} · {decl.Header} · <c>{Escape(decl.RawSignature)}</c>";

    private static string Escape(string s)
        => s.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);

    /// <summary>Turns <c>ida_highlighter.hpp</c> into <c>IdaHighlighter</c>.</summary>
    private static string GroupName(string headerFile)
    {
        string stem = Path.GetFileNameWithoutExtension(headerFile);
        var sb = new StringBuilder(stem.Length);
        bool upper = true;

        foreach (char c in stem)
        {
            if (c is '_' or '-')
            {
                upper = true;
                continue;
            }

            sb.Append(upper ? char.ToUpper(c, CultureInfo.InvariantCulture) : c);
            upper = false;
        }

        return sb.ToString();
    }
}
